results_dir: "./results"

deep_think_llm:
  llm_provider: "azureopenai"
  model: "o1"
  backend_url: "https://tryaifoundry.openai.azure.com/"
  api_version: "2024-12-01-preview"
  temperature: 0.0
  
quick_think_llm:
  llm_provider: "azureopenai"
  model: "gpt-4.1"
  backend_url: "https://tryaifoundry.openai.azure.com/"
  api_version: "2024-12-01-preview"
  temperature: 0.0

online_tools: true